Tuzov - Task 3 completed
MikhailTulupov/javaschool pull request #35
Opened 2023-01-19 05:30 UTC by sint0z

2023-01-22 05:44 UTC, MikhailTulupov requested changes

2023-01-22 05:44 UTC, MikhailTulupov commented on Task3/src/main/java/tuzov/Vec3d.java
> +    public double get_length() {
В Java принято использовать camelCase (верблюжий горб) т.е. getLength

2023-01-24 16:25 UTC, CoMakar commented
snake_case -> camelCase

2023-01-25 03:53 UTC, MikhailTulupov approved these changes
ок

2023-01-25 03:53 UTC, merged